### ISSUE TITLE
WILC1000 firmware fixes availability in microchip ASF bare metal code

### ISSUE THREAD

**Issue by jerald-pathPartner** [linux4wilc/firmware#10]
There are several issues in ASF WILC1000 firmware and driver similar to what reported here and fixed.
Is it possible to make update ASF code for WLC1000 with same changes.
I tried sing WILC1000 firmware shared here with ASF and it didnt booted. stuck at wait for firmware to boot

**Comment by AdhamAbozaeid** [comment]
All fixed issues on WILC Linux that applies to WILC ASF are also ported there, and will be released on ASF.
The Firmware not starting issue is most probably a problem of the host/driver not receiving the interrupt from WILC. Try probing the IRQ line and see if the interrupt is asserted or not.
If not, please open a salesforce ticket so that the team can help you more

**Comment by jerald-pathPartner** [comment]
hi AdhamAbozaeid,

There is any issue with  using "https://github.com/linux4wilc/firmware/blob/master/wilc1000_wifi_firmware.bin" directly  in ASF project. Please let me know your thoughts.
any idea on next ASF WILC1000 updated release schedule

**Comment by AdhamAbozaeid** [comment]
Hi @jerald-pathPartner 
You can't use the WILC Linux firmware for WILC RTOS (ASF). They are different firmwares.

**Comment by jerald-pathPartner** [comment]
hi AdhamAbozaeid,

Thanks for the confirmation
